/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-08 17:39:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("author: W3layouts\n");
      out.write("author URL: http://w3layouts.com\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\n");
      out.write("-->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zxx\">\n");
      out.write("<head>\n");
      out.write("<title>Health Plus a Medical Category Bootstrap Responsive Website Template | Home :: w3layouts</title>\n");
      out.write("<!-- for-meta-tags-->\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta name=\"keywords\" content=\"Health Plus Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \n");
      out.write("Smartphone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\n");
      out.write("		function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("<!-- //for-meta-tags-->\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("<link href=\"css/services.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("<link href=\"css/ziehharmonika.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"css/team.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("<!-- font-awesome icons -->\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \n");
      out.write("<!-- //font-awesome icons -->\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Raleway:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800\" rel=\"stylesheet\">\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,900\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("	\n");
      out.write("<body>\n");
      out.write("<div class=\"main\" id=\"home\">\n");
      out.write("<!-- banner -->\n");
      out.write("		<div class=\"header_agileinfo\">\n");
      out.write("						<div class=\"w3_agileits_header_text\">\n");
      out.write("							<ul class=\"top_agile_w3l_info_icons\">\n");
      out.write("									<li><i class=\"fa fa-home\" aria-hidden=\"true\"></i>12K Street,New York City.</li>\n");
      out.write("									<li class=\"second\"><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>(+000) 123 456 87</li>\n");
      out.write("									\n");
      out.write("									<li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i><a href=\"mailto:maria@example.com\">info@example.com</a></li>\n");
      out.write("								</ul>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("						<div class=\"agileinfo_social_icons\">\n");
      out.write("							<ul class=\"agileits_social_list\">\n");
      out.write("								<li><a href=\"#\" class=\"w3_agile_facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"agile_twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_agile_dribble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_agile_rss\"><i class=\"fa fa-rss\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"clearfix\"> </div>\n");
      out.write("			</div>				\n");
      out.write("\n");
      out.write("		<div class=\"header-bottom\">\n");
      out.write("				<nav class=\"navbar navbar-default\">\n");
      out.write("				<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("				<div class=\"navbar-header\">\n");
      out.write("				  <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("					<span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("					<span class=\"icon-bar\"></span>\n");
      out.write("					<span class=\"icon-bar\"></span>\n");
      out.write("					<span class=\"icon-bar\"></span>\n");
      out.write("				  </button>\n");
      out.write("					<div class=\"logo\">\n");
      out.write("						<h1><a class=\"navbar-brand\" href=\"index.jsp\"><span>Khajina</span>Doc <i class=\"fa fa-plus\" aria-hidden=\"true\"></i> <p>Quality Care 4U</p></a></h1>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("				<div class=\"collapse navbar-collapse nav-wil\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("					<nav class=\"menu menu--sebastian\">\n");
      out.write("					<ul id=\"m_nav_list\" class=\"m_nav menu__list\">\n");
      out.write("						<li class=\"m_nav_item menu__item menu__item--current\" id=\"m_nav_item_1\"> <a href=\"index.jsp\" class=\"menu__link\"> Home </a></li>\n");
      out.write("						<li class=\"m_nav_item menu__item\" id=\"moble_nav_item_2\"> <a href=\"about.jsp\" class=\"menu__link\"> About Us </a> </li>		\n");
      out.write("						<li class=\"m_nav_item menu__item\" id=\"moble_nav_item_4\"> <a href=\"appointment.jsp\" class=\"menu__link\">Appointment  </a> </li>\n");
      out.write("						<li class=\"m_nav_item menu__item\" id=\"moble_nav_item_3 dropdown\"> <a href=\"#\" class=\"menu__link dropdown-toggle\" data-toggle=\"dropdown\">Registration  <b class=\"caret\"></b></a> \n");
      out.write("						   <ul class=\"dropdown-menu agile_short_dropdown\">\n");
      out.write("									<li><a href=\"Patient_Registration.jsp\">As Patient </a></li>\n");
      out.write("									<li><a href=\"Doctor_Registration.jsp\">As Doctor </a></li>\n");
      out.write("								</ul>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"m_nav_item menu__item\" id=\"moble_nav_item_3 dropdown\"> <a href=\"#\" class=\"menu__link dropdown-toggle\" data-toggle=\"dropdown\">Login  <b class=\"caret\"></b></a> \n");
      out.write("						   <ul class=\"dropdown-menu agile_short_dropdown\">\n");
      out.write("									<li><a href=\"Patient_Login.jsp\">Patient Login</a></li>\n");
      out.write("									<li><a href=\"Doctor_Login.jsp\">Doctor Login</a></li>\n");
      out.write("									<li><a href=\"Admin_Login.jsp\">Admin Login</a></li>\n");
      out.write("						   </ul>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"m_nav_item menu__item\" id=\"moble_nav_item_6\"> <a href=\"contact.jsp\" class=\"menu__link\"> Contact </a> </li>\n");
      out.write("					</ul>\n");
      out.write("				</nav>\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<!-- /.navbar-collapse -->\n");
      out.write("			</nav>\n");
      out.write("	 </div>\n");
      out.write("</div>\n");
      out.write("<!-- banner -->\n");
      out.write("<!-- banner1 -->\n");
      out.write("	<div class=\"banner1 jarallax\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"services-breadcrumb\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<ul>\n");
      out.write("				<li><a href=\"index.jsp\">Home</a><i>|</i></li>\n");
      out.write("				<li>About</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<!-- //banner1 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- //banner -->\n");
      out.write("\n");
      out.write("<!-- about -->\n");
      out.write("	<div class=\"about\" id=\"about\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("				<h2 class=\"w3_heade_tittle_agile\">Welcome to our Health Plus</h2>\n");
      out.write("			<p class=\"sub_t_agileits\">Add Short Description</p>\n");
      out.write("			\n");
      out.write("			<p class=\"ab\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.Sed blandit massa vel mauris sollicitudin dignissim.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at placerat ante. Praesent nulla nunc, pretium dapibus efficitur in, auctor eget elit. Lorem ipsum dolor sit amet</p>\n");
      out.write("\n");
      out.write("			 <div class=\"about-w3lsrow\"> \n");
      out.write("				\n");
      out.write("				<div class=\"col-md-6 w3about-img\"> \n");
      out.write("				    <img src=\"images/about.jpg\" alt=\" \" class=\"img-responsive\">\n");
      out.write("				</div> \n");
      out.write("				<div class=\"col-md-6 col-sm-7 w3about-img\"> \n");
      out.write("					<div class=\"w3about-text\"> \n");
      out.write("						<h5 class=\"w3l-subtitle\">We Care About Your Health</h5>\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at placerat ante. Praesent nulla nunc, pretium dapibus efficitur in, auctor eget elit. Lorem ipsum dolor sit amet</p>\n");
      out.write("\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at placerat ante. Praesent nulla nunc, pretium dapibus efficitur in, auctor eget elit. Lorem ipsum dolor sit amet</p>\n");
      out.write("						  <div class=\"read\"><a href=\"single.jsp\" class=\"hvr-rectangle-in\">Read More</a></div>\n");
      out.write("					</div>\n");
      out.write("				</div> \n");
      out.write("				<div class=\"clearfix\"> </div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("</div>\n");
      out.write("<!-- /about-bottom -->\n");
      out.write("<!-- /girds_agileits -->\n");
      out.write("	<div class=\"Department_girds_agileits\">\n");
      out.write("		<div class=\"agile_team_grid\">	\n");
      out.write("	\n");
      out.write("					<div class=\"col-md-3 w3ls_banner_bottom_grid\">\n");
      out.write("						<img src=\"images/g1.jpg\" alt=\" \" class=\"img-responsive\" />\n");
      out.write("						<div class=\"overlay\">\n");
      out.write("							<h4>Department 1</h4>\n");
      out.write("							<ul class=\"social_agileinfo\">\n");
      out.write("								<li><a href=\"#\" class=\"w3_facebook\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_twitter\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_instagram\"><i class=\"fa fa-instagram\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_google\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("					<div class=\"col-md-3 w3ls_banner_bottom_grid\">\n");
      out.write("						<img src=\"images/g2.jpg\" alt=\" \" class=\"img-responsive\" />\n");
      out.write("						<div class=\"overlay\">\n");
      out.write("							<h4>Department 2</h4>\n");
      out.write("							<ul class=\"social_agileinfo\">\n");
      out.write("								<li><a href=\"#\" class=\"w3_facebook\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_twitter\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_instagram\"><i class=\"fa fa-instagram\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_google\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"col-md-3 w3ls_banner_bottom_grid hvr-shutter-in-horizontal\">\n");
      out.write("						<img src=\"images/g3.jpg\" alt=\" \" class=\"img-responsive\" />\n");
      out.write("						<div class=\"overlay\">\n");
      out.write("							<h4>Department 3</h4>\n");
      out.write("							<ul class=\"social_agileinfo\">\n");
      out.write("								<li><a href=\"#\" class=\"w3_facebook\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_twitter\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_instagram\"><i class=\"fa fa-instagram\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_google\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<div class=\"col-md-3 w3ls_banner_bottom_grid\">\n");
      out.write("						<img src=\"images/g4.jpg\" alt=\" \" class=\"img-responsive\" />\n");
      out.write("						<div class=\"overlay\">\n");
      out.write("							<h4>Department 4</h4>\n");
      out.write("							<ul class=\"social_agileinfo\">\n");
      out.write("								<li><a href=\"#\" class=\"w3_facebook\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_twitter\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_instagram\"><i class=\"fa fa-instagram\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_google\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<div class=\"clearfix\"></div>\n");
      out.write("	</div>\n");
      out.write("<!-- //girds_agileits -->\n");
      out.write("\n");
      out.write("	<div class=\"agile_menu\" id=\"menu\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("		<h3 class=\"w3_heade_tittle_agile\">Our Departments</h3>\n");
      out.write("		<p class=\"sub_t_agileits\">Add Short Description</p>\n");
      out.write("		<div class=\"menu_w3ls_agile_top_section\">\n");
      out.write("			<div class=\"ziehharmonika\">\n");
      out.write("			<h3>Neurology</h3>\n");
      out.write("			<div>\n");
      out.write("				  <div class=\"w3_agile_recipe-grid\">\n");
      out.write("                                  \n");
      out.write("								<div class=\"col-md-6 col-sm-6 tab-image\">\n");
      out.write("									<img src=\"images/g5.jpg\" alt=\"Medicinal\">\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6 col-sm-6 tab-info\">\n");
      out.write("								<h4>We are having department to us</h4>\n");
      out.write("									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting... </p>\n");
      out.write("									<div class=\"read\"><a href=\"#\" class=\"hvr-rectangle-in\">Read More</a></div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"clearfix\"></div>\n");
      out.write("					    </div>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<h3>Dental</h3>\n");
      out.write("			<div>\n");
      out.write("				  <div class=\"w3_agile_recipe-grid\">\n");
      out.write("                                  \n");
      out.write("								\n");
      out.write("									<div class=\"col-md-6 col-sm-6 tab-info two\">\n");
      out.write("								<h4>We are having department to us</h4>\n");
      out.write("									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting... </p>\n");
      out.write("									<div class=\"read\"><a href=\"#\" class=\"hvr-rectangle-in\">Read More</a></div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6 col-sm-6 tab-image two\">\n");
      out.write("									<img src=\"images/g6.jpg\" alt=\"Medicinal\">\n");
      out.write("								</div>\n");
      out.write("								<div class=\"clearfix\"></div>\n");
      out.write("					    </div>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<h3>Eye Care</h3>\n");
      out.write("			<div>\n");
      out.write("			 <div class=\"w3_agile_recipe-grid\">\n");
      out.write("                                  \n");
      out.write("								<div class=\"col-md-6 col-sm-6 tab-image\">\n");
      out.write("									<img src=\"images/g7.jpg\" alt=\"Medicinal\">\n");
      out.write("								</div>\n");
      out.write("									<div class=\"col-md-6 col-sm-6 tab-info\">\n");
      out.write("								<h4>We are having department to us</h4>\n");
      out.write("									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting... </p>\n");
      out.write("									<div class=\"read\"><a href=\"#\" class=\"hvr-rectangle-in\">Read More</a></div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"clearfix\"></div>\n");
      out.write("					    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<h3>Baby Care</h3>\n");
      out.write("			<div>\n");
      out.write("				  <div class=\"w3_agile_recipe-grid\">\n");
      out.write("                                  \n");
      out.write("								\n");
      out.write("								<div class=\"col-md-6 col-sm-6 tab-info two\">\n");
      out.write("								<h4>We are having department to us</h4>\n");
      out.write("									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting... </p>\n");
      out.write("									<div class=\"read\"><a href=\"#\" class=\"hvr-rectangle-in\">Read More</a></div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"col-md-6 col-sm-6 tab-image two\">\n");
      out.write("									<img src=\"images/g2.jpg\" alt=\"Medicinal\">\n");
      out.write("								</div>\n");
      out.write("								<div class=\"clearfix\"></div>\n");
      out.write("					    </div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<!-- services section -->\n");
      out.write("<div class=\"service-w3l jarallax\" id=\"service\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("	<h3 class=\"w3_heade_tittle_agile two\">What We Do Best</h3>\n");
      out.write("		<p class=\"sub_t_agileits\">Add Short Description</p>\n");
      out.write("		<div class=\"col-lg-4 col-md-4 col-sm-12 serv-agileinfo1\">\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-6 serv-wthree1\" data-aos=\"zoom-in\">\n");
      out.write("				<ul class=\"ch-grid\">\n");
      out.write("					<li>\n");
      out.write("						<div class=\"ch-item\">				\n");
      out.write("							<div class=\"ch-info\">\n");
      out.write("								<div class=\"ch-info-front ch-img-1\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i></div>\n");
      out.write("								<div class=\"ch-info-back\">\n");
      out.write("									<h5>Health Plus</h5>\n");
      out.write("									<p>Best In Services</p>\n");
      out.write("								</div>	\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				<h4 class=\"text-center\">Easy Booking</h4>\n");
      out.write("				<p class=\"text-center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat risus eu pretium commodo.</p>	\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-6 serv-wthree2\" data-aos=\"zoom-in\">\n");
      out.write("				<ul class=\"ch-grid\">\n");
      out.write("					<li>\n");
      out.write("						<div class=\"ch-item\">				\n");
      out.write("							<div class=\"ch-info\">\n");
      out.write("								<div class=\"ch-info-front ch-img-2\"><i class=\"fa fa-user-md\" aria-hidden=\"true\"></i></div>\n");
      out.write("								<div class=\"ch-info-back\">\n");
      out.write("									<h5>Health Plus</h5>\n");
      out.write("									<p>Best In Services</p>\n");
      out.write("								</div>	\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				<h4 class=\"text-center\">Experience</h4>\n");
      out.write("				<p class=\"text-center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat risus eu pretium commodo.</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clearfix\"></div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col-lg-4 col-md-4 col-sm-6 serv-agileinfo2\">\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-6 serv-wthree4\" data-aos=\"zoom-in\">\n");
      out.write("				<ul class=\"ch-grid\">\n");
      out.write("					<li>\n");
      out.write("						<div class=\"ch-item\">				\n");
      out.write("							<div class=\"ch-info\">\n");
      out.write("								<div class=\"ch-info-front ch-img-3\"><i class=\"fa fa-ambulance\" aria-hidden=\"true\"></i></div>\n");
      out.write("								<div class=\"ch-info-back\">\n");
      out.write("									<h5>Health Plus</h5>\n");
      out.write("									<p>Best In Services</p>\n");
      out.write("								</div>	\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				<h4 class=\"text-center\">Emergency Care</h4>\n");
      out.write("				<p class=\"text-center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat risus eu pretium commodo.</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clearfix\"></div>\n");
      out.write("		</div>	\n");
      out.write("		<div class=\"col-lg-4 col-md-4 col-sm-6 serv-agileinfo3\">\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-6 serv-wthree6\" data-aos=\"zoom-in\">\n");
      out.write("				<ul class=\"ch-grid\">\n");
      out.write("					<li>\n");
      out.write("						<div class=\"ch-item\">				\n");
      out.write("							<div class=\"ch-info\">\n");
      out.write("								<div class=\"ch-info-front ch-img-4\"><i class=\"fa fa-tint\" aria-hidden=\"true\"></i></div>\n");
      out.write("								<div class=\"ch-info-back\">\n");
      out.write("									<h5>Health Plus</h5>\n");
      out.write("									<p>Best In Services</p>\n");
      out.write("								</div>	\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				<h4 class=\"text-center\">DNA Testing</h4>\n");
      out.write("				<p class=\"text-center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat risus eu pretium commodo.</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-lg-12 col-md-12 col-sm-6 serv-wthree5\" data-aos=\"zoom-in\">\n");
      out.write("				<ul class=\"ch-grid\">\n");
      out.write("					<li>\n");
      out.write("						<div class=\"ch-item\">				\n");
      out.write("							<div class=\"ch-info\">\n");
      out.write("								<div class=\"ch-info-front ch-img-5\"><i class=\"fa fa-wheelchair\" aria-hidden=\"true\"></i></div>\n");
      out.write("								<div class=\"ch-info-back\">\n");
      out.write("									<h5>Health Plus</h5>\n");
      out.write("									<p>Best In Services</p>\n");
      out.write("								</div>	\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("				<h4 class=\"text-center\">General Treatment</h4>\n");
      out.write("				<p class=\"text-center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla volutpat risus eu pretium commodo.</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"clearfix\"></div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"clearfix\"></div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<!-- /services section -->\n");
      out.write("<!-- team -->\n");
      out.write("	<div class=\"team portfolio \" id=\"team\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("<h3 class=\"w3_heade_tittle_agile\">Amazing Team</h3>\n");
      out.write("		<p class=\"sub_t_agileits\">Meet Our Amazing Team...</p>\n");
      out.write("			<div class=\"w3layouts-grids\">\n");
      out.write("					<div class=\"col-md-3 wthree_team_grid\">\n");
      out.write("					<div class=\"wthree_team_grid1\">\n");
      out.write("						<div class=\"hover14 column\">\n");
      out.write("							<div>\n");
      out.write("								<figure><img src=\"images/t4.jpg\" alt=\" \" class=\"img-responsive\" /></figure>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"wthree_team_grid1_pos\">\n");
      out.write("							<h4>Rabecca Scot</h4>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"wthree_team_grid2\">\n");
      out.write("						<ul class=\"social-icons\">\n");
      out.write("							 <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-3 wthree_team_grid\">\n");
      out.write("					<div class=\"wthree_team_grid1\">\n");
      out.write("						<div class=\"hover14 column\">\n");
      out.write("							<div>\n");
      out.write("								<figure><img src=\"images/t3.jpg\" alt=\" \" class=\"img-responsive\" /></figure>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"wthree_team_grid1_pos\">\n");
      out.write("							<h4>Rosy Carl </h4>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"wthree_team_grid2\">\n");
      out.write("						<ul class=\"social-icons\">\n");
      out.write("							 <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-3 wthree_team_grid\">\n");
      out.write("					<div class=\"wthree_team_grid1\">\n");
      out.write("						<div class=\"hover14 column\">\n");
      out.write("							<div>\n");
      out.write("								<figure><img src=\"images/t2.jpg\" alt=\" \" class=\"img-responsive\" /></figure>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"wthree_team_grid1_pos\">\n");
      out.write("							<h4>David Martin</h4>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"wthree_team_grid2\">\n");
      out.write("						<ul class=\"social-icons\">\n");
      out.write("						 <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-3 wthree_team_grid\">\n");
      out.write("					<div class=\"wthree_team_grid1\">\n");
      out.write("						<div class=\"hover14 column\">\n");
      out.write("							<div>\n");
      out.write("								<figure><img src=\"images/t1.jpg\" alt=\" \" class=\"img-responsive\" /></figure>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"wthree_team_grid1_pos\">\n");
      out.write("							<h4>Reena Scot</h4>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"wthree_team_grid2\">\n");
      out.write("						<ul class=\"social-icons\">\n");
      out.write("							 <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-google-plus\"></i></a></li>\n");
      out.write("							<li><a href=\"#\"><i class=\"fa fa-linkedin\"></i></a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("		\n");
      out.write("				<div class=\"clearfix\"> </div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<!-- //team -->\n");
      out.write("<!-- stats -->\n");
      out.write("	<div class=\"stats_inner jarallax\" id=\"stats\">\n");
      out.write("	    <div class=\"container\"> \n");
      out.write("			<div class=\"inner_w3l_agile_grids\">\n");
      out.write("		<div class=\"col-md-3 w3layouts_stats_left w3_counter_grid\">\n");
      out.write("		   	<i class=\"fa fa-building-o\" aria-hidden=\"true\"></i>\n");
      out.write("			<p class=\"counter\">120</p>\n");
      out.write("			<h3>Hospital Rooms</h3>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col-md-3 w3layouts_stats_left w3_counter_grid1\">\n");
      out.write("		   <i class=\"fa fa-wheelchair\" aria-hidden=\"true\"></i>\n");
      out.write("			<p class=\"counter\">165</p>\n");
      out.write("			<h3>Wheelchair</h3>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col-md-3 w3layouts_stats_left w3_counter_grid2\">\n");
      out.write("		<i class=\"fa fa-ambulance\" aria-hidden=\"true\"></i>\n");
      out.write("			<p class=\"counter\">563</p>\n");
      out.write("			<h3>Ambulance Car</h3>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"col-md-3 w3layouts_stats_left w3_counter_grid3\">\n");
      out.write("	<i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i>\n");
      out.write("			<p class=\"counter\">245</p>\n");
      out.write("			<h3>Saved hearts</h3>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"clearfix\"> </div>\n");
      out.write("	</div>\n");
      out.write("   </div>	\n");
      out.write("</div>\n");
      out.write("<!-- //stats -->\n");
      out.write("\n");
      out.write("<!-- footer -->\n");
      out.write("	<div class=\"footer\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<h4>Subscribe to <span>Newsletter</span></h4>\n");
      out.write("			<form action=\"#\" method=\"post\">\n");
      out.write("				<input type=\"email\" name=\"Email\" placeholder=\"Enter Your Email...\" required=\"\">\n");
      out.write("				<input type=\"submit\" value=\"Send\">\n");
      out.write("			</form>\n");
      out.write("			<div class=\"agile_footer_copy\">\n");
      out.write("				<div class=\"w3agile_footer_grids\">\n");
      out.write("					<div class=\"col-md-4 w3agile_footer_grid\">\n");
      out.write("						<h3>About Us</h3>\n");
      out.write("						<p>Duis aute irure dolor in reprehenderit in voluptate velit esse.<span>Excepteur sint occaecat cupidatat \n");
      out.write("							non proident, sunt in culpa qui officia deserunt mollit.</span></p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-4 w3agile_footer_grid\">\n");
      out.write("						<h3>Contact Info</h3>\n");
      out.write("						<ul>\n");
      out.write("							<li><i class=\"fa fa-map-marker\" aria-hidden=\"true\"></i>1234k Avenue, 4th block, <span>New York City.</span></li>\n");
      out.write("							<li><i class=\"fa fa-envelope-o\" aria-hidden=\"true\"></i><a href=\"mailto:info@example.com\">info@example.com</a></li>\n");
      out.write("							<li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>+1234 567 567</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-4 w3agile_footer_grid w3agile_footer_grid1\">\n");
      out.write("						<h3>Navigation</h3>\n");
      out.write("						<ul>\n");
      out.write("							<li><span class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></span><a href=\"gallery.jsp\">Department</a></li>\n");
      out.write("							<li><span class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></span><a href=\"appointment.jsp\">Appointment</a></li>\n");
      out.write("							<li><span class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></span><a href=\"about.jsp\">About</a></li>\n");
      out.write("							<li><span class=\"fa fa-long-arrow-right\" aria-hidden=\"true\"></span><a href=\"contact.jsp\">Contact Us</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"clearfix\"> </div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"w3_agileits_copy_right_social\">\n");
      out.write("				<div class=\"col-md-6 agileits_w3layouts_copy_right\">\n");
      out.write("					<p>&copy; 2017 Health Plus. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-6 w3_agile_copy_right\">\n");
      out.write("					<ul class=\"agileits_social_list\">\n");
      out.write("								<li><a href=\"#\" class=\"w3_agile_facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"agile_twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_agile_dribble\"><i class=\"fa fa-dribbble\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("								<li><a href=\"#\" class=\"w3_agile_rss\"><i class=\"fa fa-rss\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("							</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"clearfix\"> </div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<!-- //footer -->\n");
      out.write("<a href=\"#\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\n");
      out.write(" <!-- js -->\n");
      out.write("<script src=\"js/jquery-2.2.3.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"js/ziehharmonika.js\"></script>\n");
      out.write("<script>\n");
      out.write("$(document).ready(function() {\n");
      out.write("		$('.ziehharmonika').ziehharmonika({\n");
      out.write("			collapsible: true,\n");
      out.write("			prefix: ''\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<!-- stats -->\n");
      out.write("	<script src=\"js/jquery.waypoints.min.js\"></script>\n");
      out.write("	<script src=\"js/jquery.countup.js\"></script>\n");
      out.write("		<script>\n");
      out.write("			$('.counter').countUp();\n");
      out.write("		</script>\n");
      out.write("<!-- //stats -->\n");
      out.write("	<!-- Gallery-Tab-JavaScript -->\n");
      out.write("			<script src=\"js/cbpFWTabs.js\"></script>\n");
      out.write("			<script>\n");
      out.write("				(function() {\n");
      out.write("					[].slice.call( document.querySelectorAll( '.tabs' ) ).forEach( function( el ) {\n");
      out.write("						new CBPFWTabs( el );\n");
      out.write("					});\n");
      out.write("				})();\n");
      out.write("			</script>\n");
      out.write("		<!-- //Gallery-Tab-JavaScript -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Swipe-Box-JavaScript -->\n");
      out.write("			<script src=\"js/jquery.swipebox.min.js\"></script> \n");
      out.write("				<script type=\"text/javascript\">\n");
      out.write("					jQuery(function($) {\n");
      out.write("						$(\".swipebox\").swipebox();\n");
      out.write("					});\n");
      out.write("			</script>\n");
      out.write("		<!-- //Swipe-Box-JavaScript -->\n");
      out.write("<!-- bootstrap-pop-up -->\n");
      out.write("	<div class=\"modal video-modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModal\">\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					Health Plus\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>						\n");
      out.write("				</div>\n");
      out.write("				<section>\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<img src=\"images/g9.jpg\" alt=\" \" class=\"img-responsive\" />\n");
      out.write("						<p>Ut enim ad minima veniam, quis nostrum \n");
      out.write("							exercitationem ullam corporis suscipit laboriosam, \n");
      out.write("							nisi ut aliquid ex ea commodi consequatur? Quis autem \n");
      out.write("							vel eum iure reprehenderit qui in ea voluptate velit \n");
      out.write("							esse quam nihil molestiae consequatur, vel illum qui \n");
      out.write("							dolorem eum fugiat quo voluptas nulla pariatur.\n");
      out.write("							<i>\" Quis autem vel eum iure reprehenderit qui in ea voluptate velit \n");
      out.write("								esse quam nihil molestiae consequatur.</i></p>\n");
      out.write("					</div>\n");
      out.write("				</section>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<!-- //bootstrap-pop-up -->\n");
      out.write("\n");
      out.write("<!-- flexSlider -->\n");
      out.write("	<script defer src=\"js/jquery.flexslider.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		$(window).load(function(){\n");
      out.write("		  $('.flexslider').flexslider({\n");
      out.write("			animation: \"slide\",\n");
      out.write("			start: function(slider){\n");
      out.write("			  $('body').removeClass('loading');\n");
      out.write("			}\n");
      out.write("		  });\n");
      out.write("		});\n");
      out.write("  </script>\n");
      out.write("<!-- //flexSlider -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- start-smoth-scrolling -->\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	jQuery(document).ready(function($) {\n");
      out.write("		$(\".scroll\").click(function(event){		\n");
      out.write("			event.preventDefault();\n");
      out.write("			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\n");
      out.write("		});\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<!-- start-smoth-scrolling -->\n");
      out.write("			<script src=\"js/jarallax.js\"></script>\n");
      out.write("	<script src=\"js/SmoothScroll.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		/* init Jarallax */\n");
      out.write("		$('.jarallax').jarallax({\n");
      out.write("			speed: 0.5,\n");
      out.write("			imgWidth: 1366,\n");
      out.write("			imgHeight: 768\n");
      out.write("		})\n");
      out.write("	</script>\n");
      out.write("	\n");
      out.write("	<script src=\"js/bootstrap.js\"></script>\n");
      out.write("<!-- //for bootstrap working -->\n");
      out.write("<!-- here stars scrolling icon -->\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		$(document).ready(function() {\n");
      out.write("			/*\n");
      out.write("				var defaults = {\n");
      out.write("				containerID: 'toTop', // fading element id\n");
      out.write("				containerHoverID: 'toTopHover', // fading element hover id\n");
      out.write("				scrollSpeed: 1200,\n");
      out.write("				easingType: 'linear' \n");
      out.write("				};\n");
      out.write("			*/\n");
      out.write("								\n");
      out.write("			$().UItoTop({ easingType: 'easeOutQuart' });\n");
      out.write("								\n");
      out.write("			});\n");
      out.write("	</script>\n");
      out.write("<!-- //here ends scrolling icon -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
