/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-10 10:25:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.Patientdao;
import model.Patientdata;
import java.util.List;

public final class admin_005fpatient_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.Patientdao");
    _jspx_imports_classes.add("model.Patientdata");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--A Design by W3layouts\n");
      out.write("Author: W3layout\n");
      out.write("Author URL: http://w3layouts.com\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\n");
      out.write("-->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("<title>Visitors an Admin Panel Category Bootstrap Responsive Website Template | Responsive_table :: w3layouts</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta name=\"keywords\" content=\"Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("<!-- bootstrap-css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/bootstrap.min.css\" >\n");
      out.write("<!-- //bootstrap-css -->\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<link href=\"admin/css/style.css\" rel='stylesheet' type='text/css' />\n");
      out.write("<link href=\"admin/css/style-responsive.css\" rel=\"stylesheet\"/>\n");
      out.write("<!-- font CSS -->\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\n");
      out.write("<!-- font-awesome icons -->\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/font.css\" type=\"text/css\"/>\n");
      out.write("<link href=\"admin/css/font-awesome.css\" rel=\"stylesheet\"> \n");
      out.write("<!-- //font-awesome icons -->\n");
      out.write("<script src=\"admin/js/jquery2.0.3.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<section id=\"container\">\n");
      out.write("<!--header start-->\n");
      out.write("<header class=\"header fixed-top clearfix\">\n");
      out.write("<!--logo start-->\n");
      out.write("<div class=\"brand\">\n");
      out.write("\n");
      out.write("    <a href=\"index.html\" class=\"logo\">\n");
      out.write("        VISITORS\n");
      out.write("    </a>\n");
      out.write("    <div class=\"sidebar-toggle-box\">\n");
      out.write("        <div class=\"fa fa-bars\"></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!--logo end-->\n");
      out.write("\n");
      out.write("<div class=\"nav notify-row\" id=\"top_menu\">\n");
      out.write("    <!--  notification start -->\n");
      out.write("    <ul class=\"nav top-menu\">\n");
      out.write("        <!-- settings start -->\n");
      out.write("        <li class=\"dropdown\">\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-tasks\"></i>\n");
      out.write("                <span class=\"badge bg-success\">8</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu extended tasks-bar\">\n");
      out.write("                <li>\n");
      out.write("                    <p class=\"\">You have 8 pending tasks</p>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <div class=\"task-info clearfix\">\n");
      out.write("                            <div class=\"desc pull-left\">\n");
      out.write("                                <h5>Target Sell</h5>\n");
      out.write("                                <p>25% , Deadline  12 June’13</p>\n");
      out.write("                            </div>\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"45\">\n");
      out.write("                            <span class=\"percent\"></span>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <div class=\"task-info clearfix\">\n");
      out.write("                            <div class=\"desc pull-left\">\n");
      out.write("                                <h5>Product Delivery</h5>\n");
      out.write("                                <p>45% , Deadline  12 June’13</p>\n");
      out.write("                            </div>\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"78\">\n");
      out.write("                            <span class=\"percent\"></span>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <div class=\"task-info clearfix\">\n");
      out.write("                            <div class=\"desc pull-left\">\n");
      out.write("                                <h5>Payment collection</h5>\n");
      out.write("                                <p>87% , Deadline  12 June’13</p>\n");
      out.write("                            </div>\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"60\">\n");
      out.write("                            <span class=\"percent\"></span>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <div class=\"task-info clearfix\">\n");
      out.write("                            <div class=\"desc pull-left\">\n");
      out.write("                                <h5>Target Sell</h5>\n");
      out.write("                                <p>33% , Deadline  12 June’13</p>\n");
      out.write("                            </div>\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"90\">\n");
      out.write("                            <span class=\"percent\"></span>\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li class=\"external\">\n");
      out.write("                    <a href=\"#\">See All Tasks</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <!-- settings end -->\n");
      out.write("        <!-- inbox dropdown start-->\n");
      out.write("        <li id=\"header_inbox_bar\" class=\"dropdown\">\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("                <i class=\"fa fa-envelope-o\"></i>\n");
      out.write("                <span class=\"badge bg-important\">4</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu extended inbox\">\n");
      out.write("                <li>\n");
      out.write("                    <p class=\"red\">You have 4 Mails</p>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/3.png\"></span>\n");
      out.write("                                <span class=\"subject\">\n");
      out.write("                                <span class=\"from\">Jonathan Smith</span>\n");
      out.write("                                <span class=\"time\">Just now</span>\n");
      out.write("                                </span>\n");
      out.write("                                <span class=\"message\">\n");
      out.write("                                    Hello, this is an example msg.\n");
      out.write("                                </span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/1.png\"></span>\n");
      out.write("                                <span class=\"subject\">\n");
      out.write("                                <span class=\"from\">Jane Doe</span>\n");
      out.write("                                <span class=\"time\">2 min ago</span>\n");
      out.write("                                </span>\n");
      out.write("                                <span class=\"message\">\n");
      out.write("                                    Nice admin template\n");
      out.write("                                </span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/3.png\"></span>\n");
      out.write("                                <span class=\"subject\">\n");
      out.write("                                <span class=\"from\">Tasi sam</span>\n");
      out.write("                                <span class=\"time\">2 days ago</span>\n");
      out.write("                                </span>\n");
      out.write("                                <span class=\"message\">\n");
      out.write("                                    This is an example msg.\n");
      out.write("                                </span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/2.png\"></span>\n");
      out.write("                                <span class=\"subject\">\n");
      out.write("                                <span class=\"from\">Mr. Perfect</span>\n");
      out.write("                                <span class=\"time\">2 hour ago</span>\n");
      out.write("                                </span>\n");
      out.write("                                <span class=\"message\">\n");
      out.write("                                    Hi there, its a test\n");
      out.write("                                </span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"#\">See all messages</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <!-- inbox dropdown end -->\n");
      out.write("        <!-- notification dropdown start-->\n");
      out.write("        <li id=\"header_notification_bar\" class=\"dropdown\">\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("\n");
      out.write("                <i class=\"fa fa-bell-o\"></i>\n");
      out.write("                <span class=\"badge bg-warning\">3</span>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu extended notification\">\n");
      out.write("                <li>\n");
      out.write("                    <p>Notifications</p>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <div class=\"alert alert-info clearfix\">\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\n");
      out.write("                        <div class=\"noti-info\">\n");
      out.write("                            <a href=\"#\"> Server #1 overloaded.</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <div class=\"alert alert-danger clearfix\">\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\n");
      out.write("                        <div class=\"noti-info\">\n");
      out.write("                            <a href=\"#\"> Server #2 overloaded.</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <div class=\"alert alert-success clearfix\">\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\n");
      out.write("                        <div class=\"noti-info\">\n");
      out.write("                            <a href=\"#\"> Server #3 overloaded.</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <!-- notification dropdown end -->\n");
      out.write("    </ul>\n");
      out.write("    <!--  notification end -->\n");
      out.write("</div>\n");
      out.write("<div class=\"top-nav clearfix\">\n");
      out.write("    <!--search & user info start-->\n");
      out.write("    <ul class=\"nav pull-right top-menu\">\n");
      out.write("        <li>\n");
      out.write("            <input type=\"text\" class=\"form-control search\" placeholder=\" Search\">\n");
      out.write("        </li>\n");
      out.write("        <!-- user login dropdown start-->\n");
      out.write("        <li class=\"dropdown\">\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\n");
      out.write("                <img alt=\"\" src=\"images/2.png\">\n");
      out.write("                <span class=\"username\">John Doe</span>\n");
      out.write("                <b class=\"caret\"></b>\n");
      out.write("            </a>\n");
      out.write("            <ul class=\"dropdown-menu extended logout\">\n");
      out.write("                <li><a href=\"#\"><i class=\" fa fa-suitcase\"></i>Profile</a></li>\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-cog\"></i> Settings</a></li>\n");
      out.write("                <li><a href=\"login.html\"><i class=\"fa fa-key\"></i> Log Out</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <!-- user login dropdown end -->\n");
      out.write("       \n");
      out.write("    </ul>\n");
      out.write("    <!--search & user info end-->\n");
      out.write("</div>\n");
      out.write("</header>\n");
      out.write("<!--header end-->\n");
      out.write("<!--sidebar start-->\n");
      out.write("<aside>\n");
      out.write("    <div id=\"sidebar\" class=\"nav-collapse\">\n");
      out.write("        <!-- sidebar menu start-->\n");
      out.write("        <div class=\"leftside-navigation\">\n");
      out.write("            <ul class=\"sidebar-menu\" id=\"nav-accordion\">\n");
      out.write("                <li>\n");
      out.write("                    <a class=\"active\" href=\"admin-home.jsp\">\n");
      out.write("                        <i class=\"fa fa-dashboard\"></i>\n");
      out.write("                        <span>Dashboard</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("                <li class=\"sub-menu\">\n");
      out.write("                    <a href=\"admin-seller-list.jsp\">\n");
      out.write("                        <i class=\"fa fa-book\"></i>\n");
      out.write("                        <span>Sellers</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"admin-customer-list.jsp\">\n");
      out.write("                        <i class=\"fa fa-bullhorn\"></i>\n");
      out.write("                        <span>Customers</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"sub-menu\">\n");
      out.write("                    <a href=\"admin-product-list.jsp\">\n");
      out.write("                        <i class=\"fa fa-th\"></i>\n");
      out.write("                        <span>Products</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"sub-menu\">\n");
      out.write("                    <a href=\"all-payments.jsp\">\n");
      out.write("                        <i class=\"fa fa-tasks\"></i>\n");
      out.write("                        <span>Payments</span>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("               \n");
      out.write("            </ul>            </div>\n");
      out.write("        <!-- sidebar menu end-->\n");
      out.write("    </div>\n");
      out.write("</aside>\n");
      out.write("<!--sidebar end-->\n");
      out.write("<!--main content start-->\n");
      out.write("<section id=\"main-content\">\n");
      out.write("	<section class=\"wrapper\">\n");
      out.write("		<div class=\"table-agile-info\">\n");
      out.write(" <div class=\"panel panel-default\">\n");
      out.write("    <div class=\"panel-heading\">\n");
      out.write("     Basic table\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("      <table class=\"table\" ui-jq=\"footable\" ui-options='{\n");
      out.write("        \"paging\": {\n");
      out.write("          \"enabled\": true\n");
      out.write("        },\n");
      out.write("        \"filtering\": {\n");
      out.write("          \"enabled\": true\n");
      out.write("        },\n");
      out.write("        \"sorting\": {\n");
      out.write("          \"enabled\": true\n");
      out.write("        }}'>\n");
      out.write("        <thead>\n");
      out.write("          <tr>\n");
      out.write("            <th data-breakpoints=\"xs\">ID</th>\n");
      out.write("            <th>Name</th>\n");
      out.write("            <th>Contact</th>\n");
      out.write("            <th data-breakpoints=\"xs\">Address</th>\n");
      out.write("           \n");
      out.write("          </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("         ");
List<Patientdata> list=Patientdao.getallpatient();  
      out.write('\n');
      out.write('	');
      out.write('	');
for(Patientdata p:list){ 
      out.write(" \n");
      out.write("          <tr data-expanded=\"true\">\n");
      out.write("            <td>");
      out.print(p.getId() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print(p.getName() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print(p.getContact() );
      out.write("</td>\n");
      out.write("            <td>");
      out.print(p.getAddress() );
      out.write("</td>\n");
      out.write("            \n");
      out.write("         </tr>\n");
      out.write("          \n");
      out.write("          ");
} 
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("      </table>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</section>\n");
      out.write(" <!-- footer -->\n");
      out.write("		  <div class=\"footer\">\n");
      out.write("			<div class=\"wthree-copyright\">\n");
      out.write("			  <p>© 2017 Visitors. All rights reserved | Design by <a href=\"http://w3layouts.com\">W3layouts</a></p>\n");
      out.write("			</div>\n");
      out.write("		  </div>\n");
      out.write("  <!-- / footer -->\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!--main content end-->\n");
      out.write("</section>\n");
      out.write("<script src=\"admin/js/bootstrap.js\"></script>\n");
      out.write("<script src=\"admin/js/jquery.dcjqaccordion.2.7.js\"></script>\n");
      out.write("<script src=\"admin/js/scripts.js\"></script>\n");
      out.write("<script src=\"admin/js/jquery.slimscroll.js\"></script>\n");
      out.write("<script src=\"admin/js/jquery.nicescroll.js\"></script>\n");
      out.write("<!--[if lte IE 8]><script language=\"javascript\" type=\"text/javascript\" src=\"js/flot-chart/excanvas.min.js\"></script><![endif]-->\n");
      out.write("<script src=\"admin/js/jquery.scrollTo.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
